[project]
name = "satnova"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopy>=2.4.1",
    "requests>=2.32.4",
    "rich>=14.0.0",
]
